import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Plus, Loader2, Copy } from 'lucide-react';
import { toast } from 'sonner';

interface ProductVersionsTabProps {
  productId: string;
  canEdit: boolean;
}

interface VersionRow {
  id: string;
  parent_product_id: string | null;
  versao_numero: number;
  sku: string;
  width: number | null;
  length: number | null;
  thickness: number | null;
  erp_versao: string | null;
  erp_product_code: string | null;
  active: boolean;
}

/**
 * Lista todas as versões (pai + filhos) de um item e permite criar novas variações
 * que só diferem nas dimensões (L x C x E). Demais atributos (nome, NCM, família,
 * classe, fiscal, fator KG, preço, código ERP) são herdados do pai.
 */
export function ProductVersionsTab({ productId, canEdit }: ProductVersionsTabProps) {
  const qc = useQueryClient();
  const [newW, setNewW] = useState<string>('');
  const [newL, setNewL] = useState<string>('');
  const [newT, setNewT] = useState<string>('');
  const [creating, setCreating] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ['product-versions', productId],
    queryFn: async () => {
      // Find the parent (the current product itself, or its parent if it's a child)
      const { data: self } = await supabase
        .from('products')
        .select('id, parent_product_id')
        .eq('id', productId)
        .single();
      const parentId = self?.parent_product_id ?? self?.id ?? productId;

      const { data: versions, error } = await supabase
        .from('products')
        .select('id, parent_product_id, versao_numero, sku, width, length, thickness, erp_versao, erp_product_code, active')
        .or(`id.eq.${parentId},parent_product_id.eq.${parentId}`)
        .order('versao_numero', { ascending: true });
      if (error) throw error;
      return { parentId, versions: (versions ?? []) as VersionRow[] };
    },
    enabled: !!productId,
  });

  const handleCreate = async () => {
    if (!data?.parentId) return;
    const w = Number(newW.replace(',', '.'));
    const l = Number(newL.replace(',', '.'));
    const t = Number(newT.replace(',', '.'));
    if (!w || !l || !t) {
      toast.error('Informe largura, comprimento e espessura');
      return;
    }
    // Duplicate check on existing versions
    const dup = data.versions.find(
      (v) =>
        Number(v.width) === w &&
        Number(v.length) === l &&
        Number(v.thickness) === t,
    );
    if (dup) {
      toast.error(`Já existe a versão ${dup.versao_numero} com essas dimensões`);
      return;
    }

    setCreating(true);
    try {
      // Load parent's full row to inherit metadata
      const { data: parent, error: pErr } = await supabase
        .from('products')
        .select('*')
        .eq('id', data.parentId)
        .single();
      if (pErr || !parent) throw pErr ?? new Error('Pai não encontrado');

      // Build child payload: strip identity-related fields, override dimensions
      const {
        id: _id,
        sku: _sku,
        sku_unique: _su,
        created_at: _ca,
        updated_at: _ua,
        crm_last_update_at: _cu,
        erp_versao: _ev,
        erp_hash: _eh,
        erp_last_sync_at: _es,
        erp_synced_at: _esy,
        structure_hash: _sh,
        versao_numero: _vn,
        parent_product_id: _pp,
        ...inherit
      } = parent as any;

      const childPayload: any = {
        ...inherit,
        parent_product_id: data.parentId,
        width: w,
        length: l,
        thickness: t,
        active: true,
        origem_alteracao: 'CRM',
        // sku will be auto-generated by trigger; provide placeholder
        sku: `${parent.sku || 'TEMP'}-v`,
      };

      const { error: insErr } = await supabase.from('products').insert(childPayload);
      if (insErr) throw insErr;

      toast.success('Nova versão criada');
      setNewW('');
      setNewL('');
      setNewT('');
      qc.invalidateQueries({ queryKey: ['product-versions', productId] });
      qc.invalidateQueries({ queryKey: ['products'] });
      qc.invalidateQueries({ queryKey: ['products-search'] });
    } catch (e: any) {
      toast.error(e?.message || 'Erro ao criar versão');
    } finally {
      setCreating(false);
    }
  };

  const handleToggleActive = async (v: VersionRow) => {
    if (!canEdit) return;
    const { error } = await supabase
      .from('products')
      .update({ active: !v.active, origem_alteracao: 'CRM' })
      .eq('id', v.id);
    if (error) {
      toast.error(error.message);
      return;
    }
    qc.invalidateQueries({ queryKey: ['product-versions', productId] });
    qc.invalidateQueries({ queryKey: ['products'] });
    qc.invalidateQueries({ queryKey: ['products-search'] });
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-8">
        <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
      </div>
    );
  }

  const versions = data?.versions ?? [];

  return (
    <div className="space-y-4">
      <div className="rounded-lg border bg-muted/20 p-3 text-sm text-muted-foreground">
        Versões compartilham nome, código ERP, NCM, família, classe, fator KG e
        preço base do produto principal. Apenas as <strong>dimensões</strong>{' '}
        (L × C × E) variam entre elas.
      </div>

      <div className="rounded-md border">
        <table className="w-full text-sm">
          <thead className="bg-muted/40">
            <tr className="text-left">
              <th className="px-3 py-2 w-12">Vers.</th>
              <th className="px-3 py-2">Dimensões (L × C × E)</th>
              <th className="px-3 py-2">SKU</th>
              <th className="px-3 py-2">erp_versao</th>
              <th className="px-3 py-2">Status</th>
              <th className="px-3 py-2 text-right">Ações</th>
            </tr>
          </thead>
          <tbody>
            {versions.map((v) => (
              <tr key={v.id} className="border-t">
                <td className="px-3 py-2 font-mono">
                  v{v.versao_numero}
                  {v.parent_product_id === null && (
                    <Badge variant="outline" className="ml-2 text-[10px]">
                      principal
                    </Badge>
                  )}
                </td>
                <td className="px-3 py-2">
                  {v.width ?? '—'} × {v.length ?? '—'} × {v.thickness ?? '—'}
                </td>
                <td className="px-3 py-2 font-mono text-xs">{v.sku}</td>
                <td className="px-3 py-2 font-mono text-xs">{v.erp_versao || '—'}</td>
                <td className="px-3 py-2">
                  <Badge variant={v.active ? 'default' : 'secondary'}>
                    {v.active ? 'Ativa' : 'Inativa'}
                  </Badge>
                </td>
                <td className="px-3 py-2 text-right">
                  {canEdit && v.parent_product_id !== null && (
                    <Button
                      type="button"
                      size="sm"
                      variant="ghost"
                      onClick={() => handleToggleActive(v)}
                    >
                      {v.active ? 'Inativar' : 'Reativar'}
                    </Button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {canEdit && (
        <div className="rounded-md border p-3 space-y-3">
          <div className="flex items-center gap-2 text-sm font-medium">
            <Copy className="h-4 w-4" />
            Nova versão (mesma identidade, dimensões diferentes)
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
            <div>
              <Label>Largura</Label>
              <Input
                value={newW}
                onChange={(e) => setNewW(e.target.value)}
                placeholder="ex: 15"
                inputMode="decimal"
              />
            </div>
            <div>
              <Label>Comprimento</Label>
              <Input
                value={newL}
                onChange={(e) => setNewL(e.target.value)}
                placeholder="ex: 30"
                inputMode="decimal"
              />
            </div>
            <div>
              <Label>Espessura</Label>
              <Input
                value={newT}
                onChange={(e) => setNewT(e.target.value)}
                placeholder="ex: 0,09"
                inputMode="decimal"
              />
            </div>
            <div className="flex items-end">
              <Button
                type="button"
                onClick={handleCreate}
                disabled={creating}
                className="w-full"
              >
                {creating ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <>
                    <Plus className="h-4 w-4 mr-1" /> Adicionar versão
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
