import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { MessageCircle, ClipboardList, ShoppingCart, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { useQueryClient, useMutation } from '@tanstack/react-query';
import { useAuth } from '@/hooks/useAuth';
import { WHATSAPP_ENABLED } from '@/config/features';
import type { Tables } from '@/integrations/supabase/types';

type Deal = Tables<'deals'>;

interface DealQuickActionsProps {
  deal: Deal & {
    companies?: { name: string } | null;
    contacts?: { first_name: string; last_name?: string | null; phone?: string | null; mobile?: string | null } | null;
  };
  onWhatsAppClick?: () => void;
}

export function DealQuickActions({ deal, onWhatsAppClick }: DealQuickActionsProps) {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [taskDialogOpen, setTaskDialogOpen] = useState(false);
  const [orderDialogOpen, setOrderDialogOpen] = useState(false);
  
  // Task form state
  const [taskForm, setTaskForm] = useState({
    title: '',
    description: '',
    due_date: '',
    priority: 'media' as 'baixa' | 'media' | 'alta',
  });
  
  // Order form state
  const [orderForm, setOrderForm] = useState({
    observations: '',
    delivery_date: '',
  });

  const contactPhone = deal.contacts?.mobile || deal.contacts?.phone;
  const hasWhatsApp = !!contactPhone;

  // Create task mutation
  const createTaskMutation = useMutation({
    mutationFn: async () => {
      const { error } = await supabase.from('tasks').insert({
        title: taskForm.title || `Tarefa - ${deal.name}`,
        description: taskForm.description || null,
        due_date: taskForm.due_date || null,
        priority: taskForm.priority,
        deal_id: deal.id,
        company_id: deal.company_id,
        contact_id: deal.contact_id,
        assigned_to: user?.id,
        created_by: user?.id,
        status: 'pendente',
      });
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
      toast.success('Tarefa criada com sucesso!');
      setTaskDialogOpen(false);
      resetTaskForm();
    },
    onError: () => toast.error('Erro ao criar tarefa'),
  });

  // Create order mutation
  const createOrderMutation = useMutation({
    mutationFn: async () => {
      const { error } = await supabase.from('orders').insert({
        company_id: deal.company_id,
        contact_id: deal.contact_id,
        deal_id: deal.id, // Vínculo Fase 2: pedido conhece o negócio de origem
        observations: orderForm.observations || `Pedido gerado a partir do negócio: ${deal.name}`,
        delivery_date: orderForm.delivery_date || null,
        total_value: deal.value || 0,
        created_by: user?.id,
        status: 'pendente',
        number: '', // Will be generated by trigger
        legal_entity_id: deal.legal_entity_id,
      });
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      toast.success('Pedido criado com sucesso!');
      setOrderDialogOpen(false);
      resetOrderForm();
    },
    onError: () => toast.error('Erro ao criar pedido'),
  });

  const resetTaskForm = () => {
    setTaskForm({
      title: '',
      description: '',
      due_date: '',
      priority: 'media',
    });
  };

  const resetOrderForm = () => {
    setOrderForm({
      observations: '',
      delivery_date: '',
    });
  };

  const handleWhatsAppClick = () => {
    if (onWhatsAppClick) {
      onWhatsAppClick();
    } else if (contactPhone) {
      // Fallback: open WhatsApp web
      const phone = contactPhone.replace(/\D/g, '');
      window.open(`https://wa.me/${phone}`, '_blank');
    }
  };

  return (
    <>
      <div className="flex items-center gap-2 flex-wrap">
        {/* WhatsApp Button */}
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={handleWhatsAppClick}
          disabled={!hasWhatsApp}
          className="gap-2"
          title={hasWhatsApp ? 'Enviar WhatsApp' : 'Contato sem telefone'}
        >
          <MessageCircle className="h-4 w-4 text-green-600" />
          <span className="hidden sm:inline">WhatsApp</span>
        </Button>

        {/* Create Task Button */}
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => setTaskDialogOpen(true)}
          className="gap-2"
        >
          <ClipboardList className="h-4 w-4 text-blue-600" />
          <span className="hidden sm:inline">Criar Tarefa</span>
        </Button>

        {/* Create Order Button */}
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => setOrderDialogOpen(true)}
          disabled={!deal.company_id}
          className="gap-2"
          title={deal.company_id ? 'Criar Pedido' : 'Negócio sem empresa vinculada'}
        >
          <ShoppingCart className="h-4 w-4 text-orange-600" />
          <span className="hidden sm:inline">Criar Pedido</span>
        </Button>
      </div>

      {/* Task Dialog */}
      <Dialog open={taskDialogOpen} onOpenChange={setTaskDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Nova Tarefa</DialogTitle>
          </DialogHeader>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              createTaskMutation.mutate();
            }}
            className="space-y-4"
          >
            <div>
              <Label htmlFor="task-title">Título</Label>
              <Input
                id="task-title"
                value={taskForm.title}
                onChange={(e) => setTaskForm({ ...taskForm, title: e.target.value })}
                placeholder={`Tarefa - ${deal.name}`}
              />
            </div>
            <div>
              <Label htmlFor="task-description">Descrição</Label>
              <Textarea
                id="task-description"
                value={taskForm.description}
                onChange={(e) => setTaskForm({ ...taskForm, description: e.target.value })}
                rows={3}
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="task-due-date">Data de Vencimento</Label>
                <Input
                  id="task-due-date"
                  type="date"
                  value={taskForm.due_date}
                  onChange={(e) => setTaskForm({ ...taskForm, due_date: e.target.value })}
                />
              </div>
              <div>
                <Label htmlFor="task-priority">Prioridade</Label>
                <Select
                  value={taskForm.priority}
                  onValueChange={(v) => setTaskForm({ ...taskForm, priority: v as 'baixa' | 'media' | 'alta' })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="baixa">Baixa</SelectItem>
                    <SelectItem value="media">Média</SelectItem>
                    <SelectItem value="alta">Alta</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="flex justify-end gap-2 pt-2">
              <Button type="button" variant="outline" onClick={() => setTaskDialogOpen(false)}>
                Cancelar
              </Button>
              <Button type="submit" disabled={createTaskMutation.isPending}>
                {createTaskMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Criar Tarefa
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>

      {/* Order Dialog */}
      <Dialog open={orderDialogOpen} onOpenChange={setOrderDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Novo Pedido</DialogTitle>
          </DialogHeader>
          <form
            onSubmit={(e) => {
              e.preventDefault();
              createOrderMutation.mutate();
            }}
            className="space-y-4"
          >
            <div className="p-3 bg-muted rounded-lg space-y-1 text-sm">
              <p><strong>Negócio:</strong> {deal.name}</p>
              <p><strong>Empresa:</strong> {deal.companies?.name || 'N/A'}</p>
              <p><strong>Valor:</strong> {deal.value?.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }) || 'R$ 0,00'}</p>
            </div>
            <div>
              <Label htmlFor="order-observations">Observações</Label>
              <Textarea
                id="order-observations"
                value={orderForm.observations}
                onChange={(e) => setOrderForm({ ...orderForm, observations: e.target.value })}
                placeholder={`Pedido gerado a partir do negócio: ${deal.name}`}
                rows={3}
              />
            </div>
            <div>
              <Label htmlFor="order-delivery-date">Previsão de Entrega</Label>
              <Input
                id="order-delivery-date"
                type="date"
                value={orderForm.delivery_date}
                onChange={(e) => setOrderForm({ ...orderForm, delivery_date: e.target.value })}
              />
            </div>
            <div className="flex justify-end gap-2 pt-2">
              <Button type="button" variant="outline" onClick={() => setOrderDialogOpen(false)}>
                Cancelar
              </Button>
              <Button type="submit" disabled={createOrderMutation.isPending}>
                {createOrderMutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Criar Pedido
              </Button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </>
  );
}
