import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

    const { token, action, approver_name, rejection_reason } = await req.json();

    if (!token) {
      return new Response(
        JSON.stringify({ error: 'Token é obrigatório' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (!action || !['approve', 'reject'].includes(action)) {
      return new Response(
        JSON.stringify({ error: 'Ação deve ser "approve" ou "reject"' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (action === 'approve' && !approver_name) {
      return new Response(
        JSON.stringify({ error: 'Nome do responsável é obrigatório para aprovação' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Get client IP from headers
    const clientIp = req.headers.get('x-forwarded-for') || 
                     req.headers.get('x-real-ip') || 
                     'unknown';

    console.log('Processing approval for token:', token, 'action:', action);

    // Fetch proposal by approval token
    const { data: proposal, error: proposalError } = await supabase
      .from('proposals')
      .select('*')
      .eq('approval_token', token)
      .single();

    if (proposalError || !proposal) {
      console.error('Error fetching proposal:', proposalError);
      return new Response(
        JSON.stringify({ error: 'Proposta não encontrada ou link inválido' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Check if already processed
    if (proposal.status === 'aprovada' || proposal.status === 'recusada') {
      return new Response(
        JSON.stringify({ error: 'Esta proposta já foi processada' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Check if link expired
    if (proposal.approval_token_expires_at) {
      const expiresAt = new Date(proposal.approval_token_expires_at);
      if (expiresAt < new Date()) {
        return new Response(
          JSON.stringify({ error: 'O link de aprovação expirou' }),
          { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
    }

    const now = new Date().toISOString();

    if (action === 'approve') {
      // Update proposal to approved
      const { error: updateError } = await supabase
        .from('proposals')
        .update({
          status: 'aprovada',
          approved_at: now,
          approved_by_name: approver_name,
          approved_by_ip: clientIp,
          approval_token: null, // Invalidate token after use
        })
        .eq('id', proposal.id);

      if (updateError) {
        console.error('Error updating proposal:', updateError);
        throw updateError;
      }

      // Create order from approved proposal
      const { data: newOrder, error: orderError } = await supabase
        .from('orders')
        .insert({
          number: '', // Auto-generated by trigger
          proposal_id: proposal.id,
          company_id: proposal.company_id,
          contact_id: proposal.contact_id,
          status: 'pendente',
          total_value: proposal.total_value,
          observations: proposal.observations,
        })
        .select()
        .single();

      if (orderError) {
        console.error('Error creating order:', orderError);
        // Don't throw - proposal is still approved even if order creation fails
      } else if (newOrder) {
        // Copy proposal items to order items
        const { data: proposalItems } = await supabase
          .from('proposal_items')
          .select('*')
          .eq('proposal_id', proposal.id);

        if (proposalItems && proposalItems.length > 0) {
          const orderItems = proposalItems.map((item: any) => ({
            order_id: newOrder.id,
            product_id: item.product_id,
            description: item.description,
            quantity: item.quantity,
            unit_price: item.unit_price,
            width: item.width,
            length: item.length,
            thickness: item.thickness,
            subtotal: item.subtotal,
            sort_order: item.sort_order,
          }));

          await supabase.from('order_items').insert(orderItems);
        }
      }

      return new Response(
        JSON.stringify({
          success: true,
          message: 'Proposta aprovada com sucesso!',
          order_number: newOrder?.number
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );

    } else {
      // Reject proposal
      const { error: updateError } = await supabase
        .from('proposals')
        .update({
          status: 'recusada',
          rejection_reason: rejection_reason || null,
          approval_token: null, // Invalidate token after use
        })
        .eq('id', proposal.id);

      if (updateError) {
        console.error('Error updating proposal:', updateError);
        throw updateError;
      }

      return new Response(
        JSON.stringify({
          success: true,
          message: 'Proposta recusada'
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

  } catch (error: unknown) {
    console.error('Error in proposal-approve:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ error: 'Erro interno', details: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
